
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: dify-privileged-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:dify:dify-postgres
- system:serviceaccount:dify:dify-redis
- system:serviceaccount:dify:dify-weaviate
- system:serviceaccount:dify:dify-api
- system:serviceaccount:dify:dify-worker
- system:serviceaccount:dify:dify-web
- system:serviceaccount:dify:dify-nginx
- system:serviceaccount:dify:dify-ssrf
- system:serviceaccount:dify:dify-sandbox
volumes:
- '*'